services:
  sqlserver-rd:
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    container_name: sqlserver-rd
    volumes:
      - sql_data:/var/opt/mssql
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: unless-stopped

volumes:
  sql_data: