// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RightDecisionPlayer.Data;

#nullable disable

namespace RightDecisionPlayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903202736_gamedb")]
    partial class gamedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RightDecisionPlayer.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("RightDecisionPlayer.Models.Game", b =>
                {
                    b.OwnsMany("RightDecisionPlayer.Models.Scene", "Scenes", b1 =>
                        {
                            b1.Property<Guid>("GameId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<bool>("FirstScene");

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Text")
                                .IsRequired();

                            b1.Property<string>("Title");

                            b1.HasKey("GameId", "__synthesizedOrdinal");

                            b1.ToTable("Games");

                            b1
                                .ToJson("Scenes")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsMany("RightDecisionPlayer.Models.Choice", "Choices", b2 =>
                                {
                                    b2.Property<Guid>("SceneGameId");

                                    b2.Property<int>("Scene__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<Guid>("Id");

                                    b2.Property<Guid>("NextSceneId");

                                    b2.Property<string>("Text")
                                        .IsRequired();

                                    b2.HasKey("SceneGameId", "Scene__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("SceneGameId", "Scene__synthesizedOrdinal");
                                });

                            b1.Navigation("Choices");
                        });

                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
